### PR TITLE
Dannybos fix sqlscript execution

### PR DESCRIPTION
**Pull request by danny-bos-tata**

### CODE REVIEW

**Comment by danny-bos-tata** [comment]
I have fixed the execution of the sql script to create the schema objects

**Comment by stulzq** [comment]
Thank you, could you resolve conflicts

**Comment by danny-bos-tata** [comment]
Hi, i accidently forked mysql.

These conflicts at:
Add more commits by pushing to the dannybos-fix-sqlscript-execution<https://github.com/danny-bos-tata/Hangfire.MySql.Core/tree/dannybos-fix-sqlscript-execution> branch on danny-bos-tata/Hangfire.MySql.Core<https://github.com/danny-bos-tata/Hangfire.MySql.Core>
Can be disgarded. I don’t have write access so I cannot resolve conflicts.

The fix I made is for the Oracle extension:
[cid:image001.png@01D56E11.5C811340]



Met vriendelijke groet / Kind regards,

Danny Bos

Software Engineer
SPME IMP PRC PCS

T:  +31 (0)251 499958
M: +31 (0)6 29625863

**Comment by stulzq** [comment]
I read your submission and why did you submit changes about Oracle to me? This is the MySQL repository.

**Comment by danny-bos-tata** [comment]
When I forked the repository, I had a branch of mysql all the sudden. Im not that experienced with git so I guess I made a mistake.

Met vriendelijke groet / Kind regards,

Danny Bos

Software Engineer
SPME IMP PRC PCS

T:  +31 (0)251 499958
M: +31 (0)6 29625863

**Pull request closed without merging**
